name: Python CI

on:
  push:
    branches:
      - main
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script on main branch
      if: github.ref == 'refs/heads/main'
      run: |
        python hello.py

        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs  # デプロイするディレクトリを指定

    - name: Run tests on test branch
      if: github.ref == 'refs/heads/test'
      run: |
        pytest
